### ISSUE TITLE
Closing tag not printed in full.

### ISSUE THREAD

**Issue by nickels** [RobTillaart/XMLWriter#3] opened 2020-05-24 17:58 UTC
Hi Rob, first of all thank you again for this great lib! I've been using it for a while now and since the latest release it has been acting up of me.

I have the below switch case in an endless loop which uses values from a queue in FreeRTOS.

```
            switch (XML_VALUES_RECEIVED.ACTION_TYPE)
            {
            case HEADER: // 1 HEADER
                header(TCX, XML_VALUES_RECEIVED.unixTimestamp);
                break;
            case OPEN_LAP: // 2 OPEN LAP
                openLap(TCX, XML_VALUES_RECEIVED.unixTimestamp);
                break;
            case TRACKPOINT: // 3 TRACKPOINT
                trackPoint(TCX, XML_VALUES_RECEIVED.unixTimestamp, XML_VALUES_RECEIVED.distanceInMeters);
                break;
            case CLOSE_LAP: // 4 CLOSE LAP
                closeLap(TCX, XML_VALUES_RECEIVED.durationInSeconds, XML_VALUES_RECEIVED.distanceInMeters);
                break;
            case FOOTER: // 5 FOOTER
                footer(TCX);
                tcxFile.close();
            }
```

The methods called in the above switch case below.

```
void header(XMLWriter &xmlInstance, time_t timestamp)
{
    serial_println("[XML] Writing header.");
    xmlInstance.header();
    xmlInstance.tagStart("TrainingCenterDatabase");
    xmlInstance.tagField("xsi:schemaLocation", "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2 http://www.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd");
    xmlInstance.tagField("xmlns:ns5", "http://www.garmin.com/xmlschemas/ActivityGoals/v1");
    xmlInstance.tagField("xmlns:ns3", "http://www.garmin.com/xmlschemas/ActivityExtension/v2");
    xmlInstance.tagField("xmlns:ns2", "http://www.garmin.com/xmlschemas/UserProfile/v2");
    xmlInstance.tagField("xmlns", "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2");
    xmlInstance.tagField("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance");
    xmlInstance.tagField("xmlns:ns4", "http://www.garmin.com/xmlschemas/ProfileExtension/v1");
    xmlInstance.tagEnd(NEWLINE, NOSLASH);

    xmlInstance.tagOpen("Activities");
    xmlInstance.tagStart("Activity");
    xmlInstance.tagField("Sport", "Other");
    xmlInstance.tagEnd(NEWLINE, NOSLASH);

    xmlInstance.writeNode("Id", tcxTimestamp(timestamp));
}

void openLap(XMLWriter &xmlInstance, time_t timestamp)
{
    serial_println("[XML] Opening lap.");
    xmlInstance.tagStart("Lap");
    xmlInstance.tagField("StartTime", tcxTimestamp(timestamp)); //<Lap StartTime="2019-08-15T16:04:16.000Z">
    xmlInstance.tagEnd(NEWLINE, NOSLASH);
    xmlInstance.incrIndent();

    xmlInstance.writeNode("Intensity", "Active");     //<Intensity>Active</Intensity>
    xmlInstance.writeNode("TriggerMethod", "Manual"); //<TriggerMethod>Manual</TriggerMethod>
    xmlInstance.tagOpen("Track");                     //<Track>
}

void trackPoint(XMLWriter &xmlInstance, time_t timestamp, float distance)
{
    serial_println("[XML] Writing trackpoint.");
    xmlInstance.tagOpen("Trackpoint");                      //<Trackpoint>
    xmlInstance.writeNode("Time", tcxTimestamp(timestamp)); //<Time>2019-08-15T16:04:16.000Z</Time>
    xmlInstance.writeNode("DistanceMeters", distance);      //<DistanceMeters>0.0</DistanceMeters>
    xmlInstance.tagClose();                                 //</Trackpoint>
}

void closeLap(XMLWriter &xmlInstance, time_t total_time_in_sec, float distance)
{
    serial_println("[XML] Closing lap.");
    xmlInstance.tagClose();                                                 //Track
    xmlInstance.writeNode("TotalTimeSeconds", (uint16_t)total_time_in_sec); //<TotalTimeSeconds>5</TotalTimeSeconds>
    xmlInstance.writeNode("DistanceMeters", distance);                      //<DistanceMeters>0.0</DistanceMeters>

    xmlInstance.tagStart("/Lap"); //Lap
    xmlInstance.tagEnd(NEWLINE, NOSLASH);
}

void footer(XMLWriter &xmlInstance)
{
    serial_println("[XML] Writing footer.");
    xmlInstance.tagStart("/Activity"); //Activity
    xmlInstance.tagEnd(NEWLINE, NOSLASH);

    xmlInstance.tagClose();                          //Activities
    xmlInstance.tagStart("/TrainingCenterDatabase"); //Activity
    xmlInstance.tagEnd(NEWLINE, NOSLASH);
}
```
As I'm using PlatformIO it is possible to redefine definitions of the XMLWriter package, hence PR 7e2966a7b15d0b06d4809e48f1ae3b4038761347 . The longest tag is 27 characters so I've set the length to 30 as per below.

```
build_flags =
  ;Max tag length for XML writer
  -D XMLWRITER_MAXTAGSIZE=30
```

Now the XML file is created and written to an SD card, that's all good. However it's not valid as the latest tag looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<TrainingCenterDatabase xsi:schemaLocation="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2 http://www.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd" xmlns:ns5="http://www.garmin.com/xmlschemas/ActivityGoals/v1" xmlns:ns3="http://www.garmin.com/xmlschemas/ActivityExtension/v2" xmlns:ns2="http://www.garmin.com/xmlschemas/UserProfile/v2" xmlns="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns4="http://www.garmin.com/xmlschemas/ProfileExtension/v1">
	<Activities>
	  <Activity Sport="Other">
	  <Id>2020-05-24T15:53:07.000000Z</Id>
	  <Lap StartTime="2020-05-24T15:53:07.000000Z">
	    <Intensity>Active</Intensity>
	    <TriggerMethod>Manual</TriggerMethod>
	    <Track>
	      <Trackpoint>
	        <Time>2020-05-24T15:53:07.000000Z</Time>
	        <DistanceMeters>0.00</DistanceMeters>
	      </Trackpoint>
	      <Trackpoint>
	        <Time>2020-05-24T15:53:08.000000Z</Time>
	        <DistanceMeters>0.72</DistanceMeters>
	      </Trackpoint>
	      <Trackpoint>
	        <Time>2020-05-24T15:53:10.000000Z</Time>
	        <DistanceMeters>1.47</DistanceMeters>
	      </Trackpoint>
	      <Trackpoint>
	        <Time>2020-05-24T15:53:11.000000Z</Time>
	        <DistanceMeters>2.24</DistanceMeters>
	      </Trackpoint>
	      <Trackpoint>
	        <Time>2020-05-24T15:55:11.000000Z</Time>
	        <DistanceMeters>97.48</DistanceMeters>
	      </Trackpoint>
	    </Track>
	    <TotalTimeSeconds>124</TotalTimeSeconds>
	    <DistanceMeters>97.48</DistanceMeters>
	    </Lap>
	  </Activity>
	</Activities>
</TrainingCenterDa
```

instead of:

```
<?xml version="1.0" encoding="UTF-8"?>
<TrainingCenterDatabase xsi:schemaLocation="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2 http://www.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd" xmlns:ns5="http://www.garmin.com/xmlschemas/ActivityGoals/v1" xmlns:ns3="http://www.garmin.com/xmlschemas/ActivityExtension/v2" xmlns:ns2="http://www.garmin.com/xmlschemas/UserProfile/v2" xmlns="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns4="http://www.garmin.com/xmlschemas/ProfileExtension/v1">
	<Activities>
	  <Activity Sport="Other">
	  <Id>2020-05-24T15:53:07.000000Z</Id>
	  <Lap StartTime="2020-05-24T15:53:07.000000Z">
	    <Intensity>Active</Intensity>
	    <TriggerMethod>Manual</TriggerMethod>
	    <Track>
	      <Trackpoint>
	        <Time>2020-05-24T15:53:07.000000Z</Time>
	        <DistanceMeters>0.00</DistanceMeters>
	      </Trackpoint>
	      <Trackpoint>
	        <Time>2020-05-24T15:53:08.000000Z</Time>
	        <DistanceMeters>0.72</DistanceMeters>
	      </Trackpoint>
	      <Trackpoint>
	        <Time>2020-05-24T15:53:10.000000Z</Time>
	        <DistanceMeters>1.47</DistanceMeters>
	      </Trackpoint>
	      <Trackpoint>
	        <Time>2020-05-24T15:53:11.000000Z</Time>
	        <DistanceMeters>2.24</DistanceMeters>
	      </Trackpoint>
	      <Trackpoint>
	        <Time>2020-05-24T15:55:11.000000Z</Time>
	        <DistanceMeters>97.48</DistanceMeters>
	      </Trackpoint>
	    </Track>
	    <TotalTimeSeconds>124</TotalTimeSeconds>
	    <DistanceMeters>97.48</DistanceMeters>
	    </Lap>
	  </Activity>
	</Activities>
</TrainingCenterDatabase>
```

Any thoughts?

Thanks!

**Comment by RobTillaart** [comment] 2020-05-24 18:31
Thanks for opening the issue, I will have a look.

**Comment by RobTillaart** [comment] 2020-05-24 18:40
3 thoughts:
- looks like a buffer is not flushed correctly (file closed before buffer printed or so)

- First have you tried hard code the XMLWRITER_MAXTAGSIZE to 30 in the library.
If that gives the same error it is not the passing of the parameter.

**Comment by RobTillaart** [comment] 2020-05-24 18:43
I can reproduce the error here, now diving into it.

**Comment by RobTillaart** [comment] 2020-05-24 18:46
internal buffer does hold the right value.

**Comment by RobTillaart** [comment] 2020-05-24 19:13
it prints 21 bytes of the last string for me; but only 18 for you.... strange...

AHA, The new version has internal buffering and it is not flushed. That buffer speeds up the overal performance. Its size can be set in the constructor and is default 10, maybe that is a bad choice.

OK yes, and the bug is in the demo sketch. 

**solution**
You need to add XML.flush() before closing the file on SD card.

Please verify if that solves your issue.

**Comment by nickels** [comment] 2020-05-24 20:37
Hi Rob, that’s quick! I’ll be able to test it tomorrow. Cheers.

**Comment by RobTillaart** [comment] 2020-05-25 06:40
Had all the tools needed nearby, so it was easy to verify

**Comment by nickels** [comment] 2020-05-25 06:43
Confirmed, thank you very much for your help.

```
<?xml version="1.0" encoding="UTF-8"?>
<TrainingCenterDatabase xsi:schemaLocation="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2 http://www.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd" xmlns:ns5="http://www.garmin.com/xmlschemas/ActivityGoals/v1" xmlns:ns3="http://www.garmin.com/xmlschemas/ActivityExtension/v2" xmlns:ns2="http://www.garmin.com/xmlschemas/UserProfile/v2" xmlns="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns4="http://www.garmin.com/xmlschemas/ProfileExtension/v1">
<Activities>
  <Activity Sport="Other">
  <Id>2020-05-25T06:41:04.000000Z</Id>
  <Lap StartTime="2020-05-25T06:41:04.000000Z">
    <Intensity>Active</Intensity>
    <TriggerMethod>Manual</TriggerMethod>
    <Track>
      <Trackpoint>
        <Time>2020-05-25T06:41:04.000000Z</Time>
        <DistanceMeters>0.00</DistanceMeters>
      </Trackpoint>
      <Trackpoint>
        <Time>2020-05-25T06:41:14.000000Z</Time>
        <DistanceMeters>8.33</DistanceMeters>
      </Trackpoint>
    </Track>
    <TotalTimeSeconds>10</TotalTimeSeconds>
    <DistanceMeters>8.33</DistanceMeters>
    </Lap>
    </Activity>
  </Activities>
</TrainingCenterDatabase>
```

**Closed as completed** 2020-05-25 06:43 UTC

**Comment by RobTillaart** [comment] 2020-05-25 06:49
I will update the SDcard demo adding the flush, and make a not in the docs.
